name: HAServiceProxy
version: "1.0.6"
panel_icon: "mdi:globe"
panel_title: HAServiceProxy
slug: ha-service-proxy
description: Service Proxy
url: "https://github.com/bzellman/HAServiceProxy"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:5000]/"
watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "frigate.local:5000"
schema:
  server: "match(^.+:\\d+$)"
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
