name: HAService
version: "1.0.4"
slug: ha-service-proxy
description: Proxy addon for Services
startup: application
boot: auto
ingress: true
ingress_entry: /
ingress_port: 8090
panel_title: HAServiceProxy
panel_icon: mdi:web
panel_admin: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
options:
  server: "192.168.0.205:8090"
schema:
  server: "match(^.+:\\d+$)"
services: []