name: HAService
version: "1.0.3"
panel_icon: "mdi:web"
panel_title: HAServiceProxy
slug: ha-service-proxy
description: Proxy addon for Services
url: "https://github.com/bzellman/HAServiceProxy"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8090]/"
watchdog: "http://[HOST]:[PORT:8090]/"
ingress: true
ingress_port: 8090
ingress_entry: /
panel_admin: false
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "192.168.0.205:8090"
schema:
  server: "match(^.+:\\d+$)"
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
